const mongoose = require('mongoose');

const eventSchema = new mongoose.Schema({
    _id: {
      type: mongoose.Schema.Types.ObjectId,
      auto: true // Automatically generated by MongoDB
    },
    eventName: {
      type: String,
      required: true
    },
    coordinatorName: {
      type: String,
      required: true
    },
    startDate: {
      type: Date, // Consider changing this to Date type for better validation
      required: true,
    },
    endDate: {
      type: Date, // Consider changing this to Date type for better validation
      required: true,
    },
    no_of_teams: {
      type: Number,
      required: true,
      min: 1 // Minimum number of teams should be 1
    }
  });
  
// Create the model from the schema
const Event = mongoose.model('Event', eventSchema);

module.exports = Event;
