const mongoose = require('mongoose');

const teamSchema = new mongoose.Schema({
  _id: {
    type: mongoose.Schema.Types.ObjectId,
    auto: true // Automatically generated by MongoDB
  },
  event_id: {
    type: mongoose.Schema.Types.ObjectId,
    required: true, // Reference to the corresponding event
    ref: 'Event' // This references the Event model
  },
  team_name: {
    type: String,
    required: true // Name of the team
  },
  head: {
    type: String,
    required: true // Email of the team head (captain)
  },
  captain_name: { // New field for the captain's name
    type: String,
    required: true // Name of the team captain
  },
  members: [{
    member_name: {
      type: String,
      required: true // Name of the team member
    }
  }]
});

// Create the model from the schema
const Team = mongoose.model('Team', teamSchema);

module.exports = Team;
